# Advanced Programme in Deep Learning (Foundations and Applications)
## A Program by IISc and TalentSprint
### Assignment 2: Linear Algebra

## Learning Objectives

At the end of the assignment, you will be able to
* understand matrix, types of matrix, vectors and its related operations



### Setup Steps:

In [ ]:
#@title Please enter your registration id to start: { run: "auto", display-mode: "form" }
Id = "2303583" #@param {type:"string"}

In [ ]:
#@title Please enter your password (normally your phone number) to continue: { run: "auto", display-mode: "form" }
password = "9845542371" #@param {type:"string"}

In [ ]:
#@title Run this cell to complete the setup for this Notebook
from IPython import get_ipython
import warnings
warnings.filterwarnings("ignore")

ipython = get_ipython()

notebook= "M1_AST_02_Linear_Algebra_C" #name of the notebook

def setup():
    from IPython.display import HTML, display
    display(HTML('<script src="https://dashboard.talentsprint.com/aiml/record_ip.html?traineeId={0}&recordId={1}"></script>'.format(getId(),submission_id)))
    print("Setup completed successfully")
    return

def submit_notebook():
    ipython.magic("notebook -e "+ notebook + ".ipynb")

    import requests, json, base64, datetime

    url = "https://dashboard.talentsprint.com/xp/app/save_notebook_attempts"
    if not submission_id:
      data = {"id" : getId(), "notebook" : notebook, "mobile" : getPassword()}
      r = requests.post(url, data = data)
      r = json.loads(r.text)

      if r["status"] == "Success":
          return r["record_id"]
      elif "err" in r:
        print(r["err"])
        return None
      else:
        print ("Something is wrong, the notebook will not be submitted for grading")
        return None

    elif getAnswer1() and getAnswer2() and getComplexity() and getAdditional() and getConcepts() and getComments() and getMentorSupport():
      f = open(notebook + ".ipynb", "rb")
      file_hash = base64.b64encode(f.read())

      data = {"complexity" : Complexity, "additional" :Additional,
              "concepts" : Concepts, "record_id" : submission_id,
              "answer1" : Answer1, "answer2" : Answer2, "id" : Id, "file_hash" : file_hash,
              "notebook" : notebook,
              "feedback_experiments_input" : Comments,
              "feedback_mentor_support": Mentor_support}
      r = requests.post(url, data = data)
      r = json.loads(r.text)
      if "err" in r:
        print(r["err"])
        return None
      else:
        print("Your submission is successful.")
        print("Ref Id:", submission_id)
        print("Date of submission: ", r["date"])
        print("Time of submission: ", r["time"])
        print("View your submissions: https://dlfa-iisc.talentsprint.com/notebook_submissions")
        #print("For any queries/discrepancies, please connect with mentors through the chat icon in LMS dashboard.")
        return submission_id
    else: submission_id


def getAdditional():
  try:
    if not Additional:
      raise NameError
    else:
      return Additional
  except NameError:
    print ("Please answer Additional Question")
    return None

def getComplexity():
  try:
    if not Complexity:
      raise NameError
    else:
      return Complexity
  except NameError:
    print ("Please answer Complexity Question")
    return None

def getConcepts():
  try:
    if not Concepts:
      raise NameError
    else:
      return Concepts
  except NameError:
    print ("Please answer Concepts Question")
    return None


# def getWalkthrough():
#   try:
#     if not Walkthrough:
#       raise NameError
#     else:
#       return Walkthrough
#   except NameError:
#     print ("Please answer Walkthrough Question")
#     return None

def getComments():
  try:
    if not Comments:
      raise NameError
    else:
      return Comments
  except NameError:
    print ("Please answer Comments Question")
    return None


def getMentorSupport():
  try:
    if not Mentor_support:
      raise NameError
    else:
      return Mentor_support
  except NameError:
    print ("Please answer Mentor support Question")
    return None

def getAnswer1():
  try:
    if not Answer1:
      raise NameError
    else:
      return Answer1
  except NameError:
    print ("Please answer Question 1")
    return None

def getAnswer2():
  try:
    if not Answer2:
      raise NameError
    else:
      return Answer2
  except NameError:
    print ("Please answer Question 2")
    return None


def getId():
  try:
    return Id if Id else None
  except NameError:
    return None

def getPassword():
  try:
    return password if password else None
  except NameError:
    return None

submission_id = None
### Setup
if getPassword() and getId():
  submission_id = submit_notebook()
  if submission_id:
    setup()
else:
  print ("Please complete Id and Password cells before running setup")



Setup completed successfully


### Importing required packages

In [ ]:
import numpy as np
from math import *
from numpy import array
from numpy import diag
from numpy import dot
from numpy import zeros
from numpy import linalg as la
from numpy.linalg import eig

### Types of Matrix

**Square Matrix**: In square matrix, the number of rows are equal to the number of columns.

1. Create a square matrix with elements 61 to 69.

In [ ]:

square_matrix = np.array([np.arange(61,64),np.arange(64,67),np.arange(67,70)])
# square_matrix = np.array([np.arange(61,64),np.arange(64,67), np.arange(67,70)])
print("Square Matrix:\n",square_matrix)

Square Matrix:
 [[61 62 63]
 [64 65 66]
 [67 68 69]]



**Upper Triangular Matrix**: It is a type of square matrix, where all the values below the main diagonal are 0.

**Lower Triangular Matrix**: It is a type of square matrix, where all the values above the main diagonal are 0.


2. Create an upper and lower triangular matrix of size 6x6 with random values.

In [ ]:
rand_matrix66 =np.random.rand(6,6)
print("Original Matrix:\n",rand_matrix66)
# matrix = np.random.rand(6,6)
# print("Original Matrix:\n",matrix)

# Upper triangular matrix
upper_triangular_mat=np.triu(rand_matrix66)
print("Upper Triangular Matrix:\n",upper_triangular_mat)
# upper_triangular = np.triu(matrix)
# print("Upper Triangular Matrix:\n",upper_triangular)

# Lower triangular matrix
lTria_mat=np.tril(rand_matrix66)
print("Lower Triangular Matrix:\n", lTria_mat)
# lower_triangular = np.tril(matrix)
# print("Lower Triangular Matrix:\n", lower_triangular)

Original Matrix:
 [[0.09005662 0.22645558 0.21219027 0.08684589 0.8428995  0.13741914]
 [0.35748618 0.26253657 0.38466458 0.24837731 0.52850782 0.20784115]
 [0.10754855 0.70425692 0.56516957 0.82748841 0.09815092 0.45778914]
 [0.63790541 0.09357696 0.90990325 0.19259029 0.12709405 0.25213952]
 [0.98400745 0.30731525 0.74456238 0.29815821 0.0658003  0.49661774]
 [0.07984534 0.68909499 0.1884927  0.97534813 0.65210209 0.15966383]]
Upper Triangular Matrix:
 [[0.09005662 0.22645558 0.21219027 0.08684589 0.8428995  0.13741914]
 [0.         0.26253657 0.38466458 0.24837731 0.52850782 0.20784115]
 [0.         0.         0.56516957 0.82748841 0.09815092 0.45778914]
 [0.         0.         0.         0.19259029 0.12709405 0.25213952]
 [0.         0.         0.         0.         0.0658003  0.49661774]
 [0.         0.         0.         0.         0.         0.15966383]]
Lower Triangular Matrix:
 [[0.09005662 0.         0.         0.         0.         0.        ]
 [0.35748618 0.26253657 0.     

**Diagonal Matrix**: In a diagonal matrix, all the values are zero except the diagonal values

3. Create a diagonal matrix of size 3x3 with integer valules and do the following:

  i). Create a diagonal matrix with the values above the diagonal elements.
  
  ii). Create a diagonal matrix with the values below the diagonal elements.





In [ ]:
M = np.array([(91,82,33),(63,32,53),(78,57,60)])
# M = np.array([np.arange(73,76),np.arange(32,35), np.arange(57,60)])
print("Matrix:\n",M)

# Diagonal Matrix
dM = np.diag(np.diag(M))
print("Diagonal Matrix:\n",dM)
# diagonal_matrix = np.diag(np.diag(M))

# Using k=1 for getting the diagonal matrix with the values above the diagonal elements
# [[91 82 33]
#  [63 32 53]
#  [78 57 60]] is M
# So diagonal matrix for sub matrix [82,33] [32,53] above diagonal is  [82,0],[0,53]
print("sub matirx above main diagnol:", np.diag(M,k=1))
above_matrix = np.diag(np.diag(M,k=1))

# Using k=-1 for getting the diagonal matrix with the values below the diagonal elements
below_matrix = np.diag(np.diag(M,k=-1))

# print("Diagonal Matrix:\n",diagonal_matrix)
print("Matrix Above Diagonal:\n",above_matrix)
print("Matrix Below Diagonal:\n",below_matrix)

Matrix:
 [[91 82 33]
 [63 32 53]
 [78 57 60]]
Diagonal Matrix:
 [[91  0  0]
 [ 0 32  0]
 [ 0  0 60]]
sub matirx above main diagnol: [82 53]
Matrix Above Diagonal:
 [[82  0]
 [ 0 53]]
Matrix Below Diagonal:
 [[63  0]
 [ 0 57]]


Here all the non-diagonal elements are zero.

**Identity Matrix**: A matrix of size nxn where all diagonal values are 1 and other values are 0 is an identity matrix.

4. Create a 4x4 identity matrix with integer numbers.

In [ ]:
iM=np.identity(4)
print("4X4 identity matrix:\n",iM)
# x = np.identity(4)
# print("4x4 Identity Matrix:\n", x)

y = np.identity(4,dtype=int)
print("4x4 Identity Matrix:\n", y)

4X4 identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
4x4 Identity Matrix:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


**Null Matrix**: A null matrix has all the values as zero.

5. Create a null matrix of integers with shape 6x6.

In [ ]:
nM=np.zeros(shape=(6,6), dtype=int)
print("null maatrix:\n",nM)
# null_matrix = np.zeros(shape=(6,6))
# print("Null Matrix:\n", null_matrix)

null maatrix:
 [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


### Matrix Transpose, Inverse, and Determinant

**Transpose**: Transpose operation flips the matrix over its diagonal i.e. replacing rows with coloums and vice-versa.

1. Create a matrix and find its transpose.

In [ ]:
# Creating a matrix
matrix1 = np.array([np.arange(0,3),np.arange(3,6)])
print("Matrix 1:\n", matrix1)

# Matrix transpose
print("Transpose of a Matrix: \n", matrix1.T)

Matrix 1:
 [[0 1 2]
 [3 4 5]]
Transpose of a Matrix: 
 [[0 3]
 [1 4]
 [2 5]]


**Inverse**: This operation helps to create a matrix such that when it is multiplied by the original matrix, the result is an identity matrix.

2. Find the inverse of a matrix.

In [ ]:
# Create a matrix
A = np.array([[5,6],[7,8]])

# Finding the inverse
inverse = np.linalg.inv(A)
print("Inverse of matrix:\n",inverse)

Inverse of matrix:
 [[-4.   3. ]
 [ 3.5 -2.5]]


3. Create 3x3 matrix and find the inverse of it.

In [ ]:
B = np.array([[1,9,3],[4,5,6],[7,8,9]])
print("Matrix B:\n", B)

# Finding Inverse
inverse = np.linalg.inv(B)
print("Inverse of matrix:\n",inverse)

Matrix B:
 [[1 9 3]
 [4 5 6]
 [7 8 9]]
Inverse of matrix:
 [[-0.07142857 -1.35714286  0.92857143]
 [ 0.14285714 -0.28571429  0.14285714]
 [-0.07142857  1.30952381 -0.73809524]]


**Determinant**: Determinant of a matrix is a scalar value that helps to characterize the properties of a matrix.

4. Create a matrix of size 3x3 and find the determinant of it.

  To know more about Python libraries, click [here](https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html)




In [ ]:
B = np.array([[1,2,3],[4,5,6],[7,8,9]])
D = la.det(B)
print(D)

0.0


5. Create a 4x4 matrix and slice the rows and columns to get the middle sub-matrix and find its determinant.

In [ ]:
# Create 4x4 matrix
matrix_new = np.array([np.arange(0,4),np.arange(4,8),np.arange(8,12),np.arange(12,16)])
print("Matrix:\n", matrix_new)

# Slicing of rows and columns
sliced_matrix = matrix_new[1:3,1:3]
print("Sliced Matrix:\n",sliced_matrix)

# Finding the determinant
determinant = np.linalg.det(sliced_matrix)
print("Determinant Value:\n", determinant)

Matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Sliced Matrix:
 [[ 5  6]
 [ 9 10]]
Determinant Value:
 -4.000000000000003



### Matrix Operations and Functions


### Addition

1. Create matrix and add a scalar to it.





In [ ]:
matrix1 = np.array([np.arange(27,32),np.arange(53,58),np.arange(33,38),np.arange(91,96)])
print("Original Matrix:\n",matrix1)

# Scalar Addition
Scalar_add = matrix1 + 1
print("Resulting Matrix:\n",Scalar_add)

Original Matrix:
 [[27 28 29 30 31]
 [53 54 55 56 57]
 [33 34 35 36 37]
 [91 92 93 94 95]]
Resulting Matrix:
 [[28 29 30 31 32]
 [54 55 56 57 58]
 [34 35 36 37 38]
 [92 93 94 95 96]]


2. Create two matrices as matrix1 & matrix2. Then, perform addition operation on them.










In [ ]:
# Creating matrices
matrix1 = np.array([np.arange(7,10),np.arange(24,27)])
matrix2 = np.array([np.arange(16,19),np.arange(33,36)])
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)

# Matrix Addition
Matrix_addition = matrix1 + matrix2
print("Matrix Addition: \n",Matrix_addition)

Matrix 1:
 [[ 7  8  9]
 [24 25 26]]
Matrix 2:
 [[16 17 18]
 [33 34 35]]
Matrix Addition: 
 [[23 25 27]
 [57 59 61]]


### Subtraction

3. Create a matrix of size 3x6 and subtract a scalar from it.



In [ ]:
# Creating matrices
matrix1 = np.array([np.arange(5,11), np.arange(47,53), np.arange(9,15)])
print("Matrix 1:\n", matrix1)

# Scalar Substraction
Scalar_sub = matrix1 - np.sin(np.pi/4)
print("Scalar Subtraction :\n",Scalar_sub)

Matrix 1:
 [[ 5  6  7  8  9 10]
 [47 48 49 50 51 52]
 [ 9 10 11 12 13 14]]
Scalar Subtraction :
 [[ 4.29289322  5.29289322  6.29289322  7.29289322  8.29289322  9.29289322]
 [46.29289322 47.29289322 48.29289322 49.29289322 50.29289322 51.29289322]
 [ 8.29289322  9.29289322 10.29289322 11.29289322 12.29289322 13.29289322]]


4. Create two matrices of size 2x3 and subtract second matrix from the first one.

In [ ]:
# Creating matrices
matrix1 = np.array([np.arange(0,3),np.arange(3,6)])
matrix2 = np.array([np.arange(6,9),np.arange(9,12)])
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)

# Matrix Subtraction
Matrix_subtraction = matrix1 - matrix2
print(Matrix_subtraction)

Matrix 1:
 [[0 1 2]
 [3 4 5]]
Matrix 2:
 [[ 6  7  8]
 [ 9 10 11]]
[[-6 -6 -6]
 [-6 -6 -6]]


### Division

5. Create a 4x3 matrix and divide it by a scalar.






In [ ]:
matrix1 = np.array([np.arange(6,9),np.arange(14,17),np.arange(97,100),np.arange(54,57)])
print("Matrix 1:\n", matrix1)

# Scalar Division
Scalar_div = matrix1/np.cos(np.pi/2)
print("Scalar Division: \n",Scalar_div)

Matrix 1:
 [[ 6  7  8]
 [14 15 16]
 [97 98 99]
 [54 55 56]]
Scalar Division: 
 [[9.79874361e+16 1.14318675e+17 1.30649915e+17]
 [2.28637351e+17 2.44968590e+17 2.61299830e+17]
 [1.58413022e+18 1.60046146e+18 1.61679270e+18]
 [8.81886925e+17 8.98218164e+17 9.14549404e+17]]


6. Create two matrices and divide the first matrix by the second one.

In [ ]:
# Creating matrices
matrix1 = np.array([np.arange(18,21),np.arange(32,35)])
matrix2 = np.array([np.arange(6,9),np.arange(9,12)])
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)

# Matrix Division
Matrix_div = matrix1/matrix2
print(Matrix_div)

Matrix 1:
 [[18 19 20]
 [32 33 34]]
Matrix 2:
 [[ 6  7  8]
 [ 9 10 11]]
[[3.         2.71428571 2.5       ]
 [3.55555556 3.3        3.09090909]]


### Multiplication

7. Create a matrix and mulitply it by a Scalar.




In [ ]:
matrix1 = np.array([np.arange(121,126),np.arange(75,80)])
print("Matrix 1:\n", matrix1)

# Scalar Product
Scalar_product = matrix1*np.sin(3*np.pi/4)
print("Scalar Product:\n", Scalar_product)

Matrix 1:
 [[121 122 123 124 125]
 [ 75  76  77  78  79]]
Scalar Product:
 [[85.55992052 86.2670273  86.97413409 87.68124087 88.38834765]
 [53.03300859 53.74011537 54.44722215 55.15432893 55.86143571]]


Multiplication of two matrices is shown in the below diagram:



$A.B = \begin{bmatrix}
a & b\\
c & d\\
\end{bmatrix} \begin{bmatrix}
e & f\\
g & h\\
\end{bmatrix} = \begin{bmatrix}
ae+ bg & af+bh\\
ce+dg & cf+dh\\
\end{bmatrix}$

8. Create two matrices and multiply them.

  Note: Here, the corresponding elements are not multiplied. The multiplication rules are different from addition, subtraction, and division.

In [ ]:
# Creating matrices
matrix1 = np.array([np.arange(5,9),np.arange(2,6)])
matrix2 = np.array([np.arange(6,8),np.arange(12,14),np.arange(4,6),np.arange(1,3)])
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)

# Dot Product
Dot_product = np.dot(matrix1, matrix2)
print("Dot Product: \n",Dot_product)

Matrix 1:
 [[5 6 7 8]
 [2 3 4 5]]
Matrix 2:
 [[ 6  7]
 [12 13]
 [ 4  5]
 [ 1  2]]
Dot Product: 
 [[138 164]
 [ 69  83]]


### Please answer the questions below to complete the experiment:




Consider the statements given below and answer Q1.


A. Every skew-symmetric matrix of odd order is non-singular

B. If determinant of a square matrix is non-zero, then it is non singular

C. Adjoint of symmetric matrix is symmetric

D. Adjoint of a diagonal matrix is diagonal

In [ ]:
#@title Q.1. Which of the above statements is/are False?
Answer1 = "Only A" #@param ["","Only A","Both A & B","Only B", "Only C", "Only D", "Both B & C"]


Consider the matrix A and the values of a, b, and c given below for answering Q.2.

$A = \begin{bmatrix}
0 & 2b & c   \\
a & b & -c   \\
a & -b & c   \\
\end{bmatrix}$

<br>

A). a = $\pm \frac{1}{\sqrt{6}} $, b = $\pm \frac{1}{\sqrt{2}}$ , c = $\pm \frac{1}{\sqrt{2}} $


<br>

B). a = $\pm \frac{1}{\sqrt{6}} $, b = $\pm \frac{1}{\sqrt{3}}$ , c = $\pm \frac{1}{\sqrt{2}} $


<br>

C). a = $\pm \frac{1}{\sqrt{2}} $, b = $\pm \frac{1}{\sqrt{6}}$ , c = $\pm \frac{1}{\sqrt{3}} $

<br>

D). a = $\pm \frac{1}{\sqrt{2}} $, b = $\pm \frac{1}{\sqrt{2}}$ , c = $\pm \frac{1}{\sqrt{2}} $

In [ ]:
#@title Q.2. If 'A' is an orthogonal matrix, then, what will be the values of a, b, and c.
Answer2 = "Only C" #@param ["","Only A","Only B","Only C","Only D", "None of the above"]


In [ ]:
#@title How was the experiment? { run: "auto", form-width: "500px", display-mode: "form" }
Complexity = "Good, But Not Challenging for me" #@param ["","Too Simple, I am wasting time", "Good, But Not Challenging for me", "Good and Challenging for me", "Was Tough, but I did it", "Too Difficult for me"]


In [ ]:
#@title If it was too easy, what more would you have liked to be added? If it was very difficult, what would you have liked to have been removed? { run: "auto", display-mode: "form" }
Additional = "i am good" #@param {type:"string"}


In [ ]:
#@title Can you identify the concepts from the lecture which this experiment covered? { run: "auto", vertical-output: true, display-mode: "form" }
Concepts = "Yes" #@param ["","Yes", "No"]


In [ ]:
#@title  Text and image description/explanation and code comments within the experiment: { run: "auto", vertical-output: true, display-mode: "form" }
Comments = "Very Useful" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]


In [ ]:
#@title Mentor Support: { run: "auto", vertical-output: true, display-mode: "form" }
Mentor_support = "Very Useful" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]


In [ ]:
#@title Run this cell to submit your notebook for grading { vertical-output: true }
try:
  if submission_id:
      return_id = submit_notebook()
      if return_id : submission_id = return_id
  else:
      print("Please complete the setup first.")
except NameError:
  print ("Please complete the setup first.")

Your submission is successful.
Ref Id: 408
Date of submission:  20 Jun 2024
Time of submission:  09:27:09
View your submissions: https://dlfa-iisc.talentsprint.com/notebook_submissions
